### ISSUE TITLE
How to access moonbox with davinci?

### ISSUE THREAD

**Issue by Holy-Shine** [running-elephant/moonbox#91]
davinci client in LAN.
local mode(None yarn cluster).
URL=？ PORT=?
Any additional configuration？

**Comment by gnawoal** [comment]
the url is `jdbc:moonbox://moonboxmasterIP:10010/database?islocal=true`
more details please refer to https://edp963.github.io/moonbox/integration-davinci.html

**Comment by Holy-Shine** [comment]
thanks, it works.
